# Generated by Django 2.1.4 on 2019-01-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_info',
            field=models.TextField(default=''),
        ),
    ]
